export PATH=$HOME/.sf_bin:$PATH

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

export ZSH=/Users/sfzhou/.oh-my-zsh
ZSH_THEME=""

COMPLETION_WAITING_DOTS="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(git textmate)

source $ZSH/oh-my-zsh.sh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# ssh
export SSH_KEY_PATH="~/.ssh/rsa_id"

# Fasd
fasd_cache="$HOME/.fasd-init-bash"
if [ "$(command -v fasd)" -nt "$fasd_cache" -o ! -s "$fasd_cache" ]; then
  fasd --init posix-alias zsh-hook zsh-ccomp zsh-ccomp-install zsh-wcomp zsh-wcomp-install >| "$fasd_cache"
fi
source "$fasd_cache"
unset fasd_cache

# RamDisk
if ! test -d /t ; then
    diskutil erasevolume HFS+ 'RamDisk' `hdiutil attach -nomount ram://2097152`
    mkdir -p /t/Temp/Blog/public
    mkdir -p /t/Temp/Thesis
    mkdir -p /t/Temp/TMI
    mkdir -p /t/Temp/Quina
    mkdir -p /t/Temp/FPGA/RDAS/cache
fi

# Alias
alias q="exit"
alias c="cd ~"
alias d="cd .. && ll"

alias qr="node /Users/sfzhou/Work/Front.End/Learning.Node.js/1.Tools/3.qr.code.generator"
alias run="/usr/local/bin/python3 /Users/sfzhou/Code/07_Python/07_CppLab/run.py"

alias gp="git pull"
alias gd="git diff"
alias gs="git status"
alias gco="git checkout"
alias gpm="git push"
alias gc="git add --all && git commit -m"

alias python="python -B"
alias python3="python3 -B"

autoload -U promptinit
promptinit
prompt pure
